spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ezfarmdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
app:
  auth:
    tokenSecret: secretKey
    tokenExpirationMsec: 999999