spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ezfarmdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

  #logging.level:
  #  org.hibernate.SQL: debug
